version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: pinster-db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - default
  web:
    build: .
    container_name: pinster-server
    ports:
      - "18080:8080"
    depends_on:
      - mysql
    networks:
      - default

