spring:
  datasource:
    url: jdbc:mysql://pinster-db:3306/pinster
    username: root
    password: root
logging:
  level:
    org.springframework.jdbc: DEBUG
storage:
  path: src/main/resources/storage/